dataSource:
  driverClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  url: jdbc:mysql://shikin-bank.cf5chnrkklpf.ap-northeast-1.rds.amazonaws.com:3306/liu_demo_attendance?characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
  username: admin
  password: demoliu2020
  poolsize: 16
  maxWait: 2000
